create table if not exists board_column (
  id          bigint primary key generated by default as identity,
  name        varchar not null,
  position    smallint not null,
  board_id    bigint not null references board(id),
  created_at  timestamptz not null default current_timestamp,
  updated_at  timestamptz not null default current_timestamp,
  constraint nonnegative_position check (position >= 0)
);

create unique index if not exists board_column_name_board_id_unique_idx on board_column(name, board_id);

create trigger board_column_set_updated_at_trigger
before update on board_column
for each row
execute procedure set_updated_at();
