create table if not exists board (
  id          bigint primary key generated by default as identity,
  name        varchar not null,
  app_user_id bigint not null references app_user(id),
  created_at  timestamptz not null default current_timestamp,
  updated_at  timestamptz not null default current_timestamp
);

create unique index if not exists board_name_app_user_id_unique_idx on board(name, app_user_id);

create trigger board_set_updated_at_trigger
before update on board
for each row
execute procedure set_updated_at();
