create table if not exists subtask (
  id          bigint primary key generated by default as identity,
  title       varchar not null,
  completed   boolean not null default false,
  task_id     bigint not null references task(id) on delete cascade,
  created_at  timestamptz not null default current_timestamp,
  updated_at  timestamptz not null default current_timestamp,
  constraint nonempty_title check (title <> '')
);

create unique index if not exists subtask_task_id_title_unique_idx on subtask(task_id, title);

create trigger subtask_set_updated_at_trigger
before update on subtask
for each row
execute procedure set_updated_at();
