create table if not exists app_user (
  id          bigint    primary key generated by default as identity,
  created_at  timestamptz not null default current_timestamp,
  updated_at  timestamptz not null default current_timestamp
);

create trigger app_user_set_updated_at_trigger
before update on app_user
for each row
execute procedure set_updated_at();
