create table if not exists board (
  id          bigint primary key generated by default as identity,
  name        varchar not null,
  app_user_id bigint not null references app_user(id) on delete cascade,
  created_at  timestamptz not null default current_timestamp,
  updated_at  timestamptz not null default current_timestamp,
  constraint nonempty_name check (name <> '')
);

create unique index if not exists board_app_user_id_name_unique_idx on board(app_user_id, name);

create trigger board_set_updated_at_trigger
before update on board
for each row
execute procedure set_updated_at();
